name: RAG LLM Pipeline CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-artifacts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y ffmpeg tesseract-ocr libgl1 libglib2.0-0

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        pytest rag_llm_api_pipeline/tests --junitxml=test-results.xml

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results.xml

    - name: Upload generated files
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: processed-manuals
        path: rag_llm_api_pipeline/data/manuals/
